import type { Metadata } from 'next';
import { Roboto, Roboto_Mono } from 'next/font/google';
import './globals.css';

const robotoSans = Roboto({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const robotoMono = Roboto_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Sacola Cheia',
	// description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-BR'>
			<body
				className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
